# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  # -   repo: https://github.com/pre-commit/pre-commit-hooks
  #     rev: v2.0.0
  #     hooks:
  #     - id: flake8